### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by iamwhitebeard** [cleanbrowsing/dnsperftest#1]
When running the shell script on windows 10 using git bash, it keeps showing command not found.
![image](https://user-images.githubusercontent.com/34242565/38208399-8ce635fe-36ce-11e8-8393-b2ec213d6708.png)

**Comment by cleanbrowsing** [comment]
You need to install the dig utility. Also, it seems to be missing "expr" command.

Not familiar with Windows 10 enough to help. Only tested on Linux and Mac.
