### ISSUE TITLE
Repeated DNS Server Test Shown

### ISSUE THREAD

**Issue by RuthlessRuler** [cleanbrowsing/dnsperftest#25]
I am using "Bash on Ubuntu on Windows" on Windows 10 v1709. I have my defauly DNS Server changed yesterday to 1.1.1.1 and alterantive to Open Dns One. IDK why but Cloudflare was tested 3 times, Open DNS 2x.

This is My result:
![image](https://user-images.githubusercontent.com/20885012/38382044-5559869a-3926-11e8-87ac-5b7682f72b41.png)

**Comment by cleanbrowsing** [comment]
That's because you likely had both configured on your /etc/resolv.conf. Can you confirm? We get the current resolvers to compare..

**Comment by frnkblk** [comment]
One possible improvement to script is to add an asterisk to the resolvers pulled from the system.
Another possible improvement is to de-dupe the test list. I know my Windows Linux bash does 192.168.0.1 twice. =)

**Comment by 1623csK** [comment]
I am not a good expirience for this writing letter for constitution purposes because of learning my self.  About require to do this good story just I say very sorry sir°
