### ISSUE TITLE
IPv6 addresses result in misaligned columns

### ISSUE THREAD

**Issue by frnkblk** [cleanbrowsing/dnsperftest#26]
The script apparently pulls the system's default DNS server entries. In my case, one of those is an IPv6 address (2607:fe28:0:1000::5), and because its length, pushes the columns over, so the recommend sort doesn't work correctly:

root@frankb-PC:/mnt/c/Users/fbulk/dnsperftest# bash ./dnstest.sh | sort -k 22 -n
2607:fe28:0:1000::519 ms   40 ms   22 ms   10 ms   31 ms   9 ms    24 ms   47 ms   9 ms    65 ms     27.60
                  test1   test2   test3   test4   test5   test6   test7   test8   test9   test10  Average
premier2          16 ms   14 ms   12 ms   13 ms   13 ms   10 ms   9 ms    11 ms   13 ms   11 ms     12.20

**Comment by tssva** [comment]
Try `bash dnstest.sh | awk '{print $NF,$0}' | sort -n | cut -f2- -d' '`. This should work no matter the number of columns.

**Comment by frnkblk** [comment]
Thanks!

**Comment by dlenski** [comment]
You might be interested in #52, where I added a list of default IPv6 providers to test, using the symlink `dnstest6.sh`.
