### ISSUE TITLE
Cloudflare test fails if default IP of 1.1.1.1 is consumed by other devices

### ISSUE THREAD

**Issue by frnkblk** [cleanbrowsing/dnsperftest#27]
The Cloudflare test fails if default IP of 1.1.1.1 is consumed by other (misconfigured) devices.
Perhaps the Cloudflare IP you use should be 1.0.0.1, to avoid that issue.

This is what it looks like because service provider's router also has 1.1.1.1 on it and that IP doesn't respond to DNS queries.

root@frankb-PC:/mnt/c/Users/fbulk/dnsperftest# bash ./dnstest.sh
                  test1   test2   test3   test4   test5   test6   test7   test8   test9   test10  Average
192.168.0.1       19 ms   25 ms   14 ms   30 ms   30 ms   38 ms   24 ms   23 ms   24 ms   24 ms     25.10
cloudflare        1000 ms 1000 ms 1000 ms 1000 ms 1000 ms 1000 ms 1000 ms 1000 ms 1000 ms 1000 ms   1000.00
level3            50 ms   41 ms   102 ms  49 ms   49 ms   39 ms   62 ms   41 ms   52 ms   42 ms     52.70

**Comment by cleanbrowsing** [comment]
Cloudflare uses 1.1.1.1 by default, so even if it fails, it is good to show so people are aware that they have an issue on their network. Keeping it as I also think the % of users with this problem is very small by now.
