### ISSUE TITLE
Issue on Ubuntu

### ISSUE THREAD

**Issue by rahlquist** [cleanbrowsing/dnsperftest#3]
Error recieved 

./dnstest.sh: 1: ./dnstest.sh: Syntax error: redirection unexpected

This is due to the shell not having <<< by default on ubuntu. See https://stackoverflow.com/questions/2462317/bash-syntax-error-redirection-unexpected for reference. Changing line 1 to bash worked for me.

**Comment by cleanbrowsing** [comment]
Thanks! You can also run as:

    bash ./dnstest.sh
