### ISSUE TITLE
How to submit results?

### ISSUE THREAD

**Issue by davemac** [cleanbrowsing/dnsperftest#35]
[In the DNS Performance Results file](https://github.com/cleanbrowsing/dnsperftest/blob/master/results.md), it says 'Feel free to add yours'

What is the preferred way to submit results?

**Comment by WebSpider** [comment]
I would think a pullrequest on the file would be easiest

**Comment by cleanbrowsing** [comment]
Yes, a pull request is the best way to update that file.

thanks,
