### ISSUE TITLE
List package deps in readme

### ISSUE THREAD

**Issue by jeefberkey** [cleanbrowsing/dnsperftest#4]
In a fresh Ubuntu container, I had to install `git`, `bc`, and `dnsutils`. It would be great if these were mentioned ahead of time.

**Comment by cleanbrowsing** [comment]
Mind sending a PR with the commands you used to install those on Ubuntu? Easier than me guessing as I don't have an Ubuntu server handy.

**Comment by jeefberkey** [comment]
I was just preparing to, but it looks like you've done it already. Thanks :)
