### ISSUE TITLE
Perform a DNSSEC resolver test

### ISSUE THREAD

**Issue by semente** [cleanbrowsing/dnsperftest#47]
A test validation using `dig`:

    dig sigok.verteiltesysteme.net @127.0.0.1 (should return A record)
    dig sigfail.verteiltesysteme.net @127.0.0.1 (should return SERVFAIL)

From: http://dnssec.vs.uni-due.de/

**Comment by thomasmerz** [comment]
@semente , please explain us for what reason? What is the purpose of performing a DNSSEC resolver test for `dnstest.sh`?

**Comment by semente** [comment]
@thomasmerz , nevermind, it is seems not the scope of this tool.
