### ISSUE TITLE
Please add NextDNS to the list of tested servers

### ISSUE THREAD

**Issue by timkgh** [cleanbrowsing/dnsperftest#63]
NextDNS:
45.90.28.0
45.90.30.0

**Comment by mtzfederico** [comment]
I created PR #64 that fixes this issue. It just needs to be merged but that hasn't happened in a while. If you want to keep using dnsperftest I recommend you modify your own code or clone my fork that has this issue fixed.

**Comment by cleanbrowsing** [comment]
Merged. Thanks!
